
Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
	web.vm.network "private_network", ip: "192.168.56.101"
	web.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
	web.vm.network :forwarded_port, guest: 80, host: 8080, id: "http"
	web.vm.synced_folder "./wordpress3", "/var/www/html/wordpress"
	web.vm.synced_folder "./nginx", "/home/vagrant/nginx"
	web.vm.provider "virtualbox" do |vb|
	 vb.name = "web_vm"
	 vb.cpus = 1
     vb.memory = "512"
	 vb.gui = false
   end
   web.vm.provision "shell", inline: "apt-get update && apt-get install -y python-minimal"
   web.vm.provision :ansible do |ansible|
        # Disable default limit to connect to all the machines
        ansible.limit = "all"
        ansible.playbook = "web.yml"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
	db.vm.network "private_network", ip: "192.168.56.100"
	db.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"
	db.vm.synced_folder "./db/dump", "/home/vagrant/dump"
	db.vm.provider "virtualbox" do |vb|
	 vb.name = "db_vm"
	 vb.cpus = 1
     vb.memory = "512"
	 vb.gui = false
   end
   db.vm.provision "shell", inline: "apt-get update && apt-get install -y python-minimal"
   db.vm.provision :ansible do |ansible|
        ansible.limit = "all"
        ansible.playbook = "db.yml"
  end
end
